version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: e-receipt-postgres-demo
    environment:
      POSTGRES_DB: ${RECEIPT_DATASOURCE_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${RECEIPT_API_USER_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${RECEIPT_DATASOURCE_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - e-receipt-network

  e-receipt-admin-api:
    build: .
    image: ghcr.io/devonshin/demo-e-receipt-admin-api:latest
    container_name: demo-e-receipt-admin-api
    user: "1000:1000"
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - e-receipt-network

volumes:
  postgres_data:

networks:
  e-receipt-network:
    driver: bridge
